const INCREMENTO = "INCREMENTO";
const DECREMENTO = "DECREMENTO";
const INCREMENTOINPAR = "INCREMENTOINPAR";
const INCREMENTOASYNC = "INCREMENTOASYNC";

module.exports = {
  INCREMENTO,
  DECREMENTO,
  INCREMENTOINPAR,
  INCREMENTOASYNC,
};
