const ADD_MOVIE_FAVORITE = "ADD_MOVIE_FAVORITE";
const GET_MOVIES = "GET_MOVIES";
const GET_MOVIE_DETAIL = "GET_MOVIE_DETAIL";
const REMOVE_MOVIE_FAVORITE = "REMOVE_MOVIE_FAVORITE";

module.exports = {
  ADD_MOVIE_FAVORITE,
  GET_MOVIES,
  GET_MOVIE_DETAIL,
  REMOVE_MOVIE_FAVORITE,
};
